// auth types
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';

export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';

export const HIDE_ALERT = 'HIDE_ALERT';
export const SHOW_ALERT = 'SHOW_ALERT';

// app types
export const UPLOAD_FILE_SUCCESSFUL = 'UPLOAD_FILE_SUCCESSFUL';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';
export const UPLOAD_FILE = 'UPLOAD_FILE';

export const CREATE_LINK_SUCCESSFUL = 'CREATE_LINK_SUCCESSFUL';
export const CREATE_LINK_ERROR = 'CREATE_LINK_ERROR';

export const CLEAN_STATE = 'CLEAN_STATE';


